notion_token: 
notion_database_id: 
vault_folder: "/home/duden/KnowledgeWorkflow/vault/template"
script_path: "/home/duden/KnowledgeWorkflow/scripts/publish_to_notion.py"
python_path: "/home/duden/KnowledgeWorkflow/scripts/venv/bin/python"
telegram_token: 
telegram_chat_id: 
